### ISSUE TITLE
Support hash routing

### ISSUE THREAD

**Issue by EndBug** [chubin/qrenco.de#5]
As of now, the website doesn't support URLs with hashes: https://qrenco.de/http://example.com/#/hash points to http://example.com/, and you can see that https://qrenco.de/http://example.com/#/hash and https://qrenco.de/http://example.com/ have the same output

**Comment by chubin** [comment]
`#` is intended for the browser and not for the server, that's why `curl` truncating it. You can't pass URL with `#` to the server.
More on this: https://unix.stackexchange.com/questions/453753/


You can still pass it as a string to stdin.
